// <auto-generated />
namespace Daily_Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class contacttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contacttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201905150835425_contacttable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
